production:
  environment: production
  elasticsearch_url: "http://localhost:9200"
development:
  environment: sandbox
  elasticsearch_url: "http://localhost:9200"
test:
  environment: test
  elasticsearch_url: "http://localhost:9200"
