# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a5da7691f0858845c88866a2f85274c4788c7f804801b39f25603ac94fc3a0f21f2501dc5bfcfe8a8bc24c30aa68f15f97f9704d9201b03fb27627c3b58765f

test:
  secret_key_base: 1dfe113b5c46ee02e7fefd50ce7eea8eeab227969faabbc4b16ce0620d0c1a3ea8ef3ef12d7b3ed0d6981b314997031b994f254118728da5f7754fffd344c41b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
